// Per-session Posts state.
// Mirrors the subscribe/notify pattern used by src/library.js.
//
// Public API:
//   getPosts(sessionId)         → Post[]  (seeds from mocks on first access)
//   addPostDraft(sessionId, {network, text[], hashtags[]}) → Post
//   attachImageToDraft(sessionId, postId, imageUrl)
//   subscribe(sessionId, fn)    → unsubscribe fn

import { postsBySession as seedPostsBySession, recentSessions as seedRecentSessions } from "./mocks.js?v=38";
import { isNewUser } from "./user-mode.js?v=22";

// Demo session ids — only these get the seeded posts mock. Brand-new
// conversations start empty (cf. library.js for the same rationale).
const DEMO_SESSION_IDS = new Set(seedRecentSessions.map((s) => s.id));

// --- Module state -------------------------------------------------------

const store = new Map(); // sessionId → Post[]
const subs = new Map(); // sessionId → Set<fn>

let idCounter = 0;
function newId() {
  idCounter += 1;
  return `draft-${Date.now().toString(36)}-${idCounter}`;
}

// --- Public API ---------------------------------------------------------

export function getPosts(sessionId) {
  if (!store.has(sessionId)) seed(sessionId);
  return store.get(sessionId);
}

// Prepend a new draft post (generated by the conversational draft flow).
// Returns the created post object so callers can reference its id.
export function addPostDraft(
  sessionId,
  { network, text, hashtags = [], clipRef = null, subtitleStyle = null, format = null },
) {
  const posts = getPosts(sessionId);
  // Use the first existing post's author as a template — keeps the demo
  // looking like it belongs to the same person.
  const templateAuthor = posts[0]?.author || {
    name: "You",
    title: "",
    initials: "YO",
    connection: "1st",
    visibility: "public",
  };
  const draft = {
    id: newId(),
    author: templateAuthor,
    network: network === "x" ? "twitter" : network,
    status: "ready",
    timeLabel: "just now",
    text: Array.isArray(text) ? text : [text],
    hashtags,
    cta: "",
    hasImage: false,
    stats: { likes: 0, comments: 0, reposts: 0 },
    // Optional video-source reference — set by the Video Clips modal so the
    // post card renders a native-feeling video player in place of the
    // "Generate an image" placeholder. `hue` drives the faux thumbnail's
    // gradient color so the demo looks like a real frame extraction.
    clipRef: clipRef
      ? {
          start: clipRef.start,
          end: clipRef.end,
          sourceName: clipRef.sourceName,
          hue: typeof clipRef.hue === "number" ? clipRef.hue : 24,
        }
      : null,
    // Subtitle preset chosen by the user after the "Add subtitles?" turn.
    // Only meaningful when clipRef is set; carries the style name so the
    // post-card can show a "Subtitles · Bold" metadata pill under the
    // video PIP. `null` or "none" → no badge.
    subtitleStyle: subtitleStyle || null,
    // Export aspect ratio chosen in the clip-draft flow (e.g. "9:16").
    // Only meaningful when clipRef is set; the post-card uses it to pick a
    // portrait vs landscape video frame. `null` → fall back to the
    // network's default orientation.
    format: format || null,
  };
  posts.unshift(draft);
  notify(sessionId);
  return draft;
}

// Apply a subtitle style preset to one or many existing drafts. Used by
// the "Add subtitles to your clips?" question that posts in the assistant
// thread after the user has drafted N posts from clips. `style` is one of
// "bold" | "clean" | "caption" | "none" (or null to clear).
export function setSubtitleStyle(sessionId, postIds, style) {
  const posts = getPosts(sessionId);
  const ids = Array.isArray(postIds) ? postIds : [postIds];
  let touched = false;
  for (const id of ids) {
    const post = posts.find((p) => p.id === id);
    if (post) {
      post.subtitleStyle = style === "none" ? null : style || null;
      touched = true;
    }
  }
  if (touched) notify(sessionId);
}

// Update a post's image (called from the generate-image modal callback).
export function attachImageToDraft(sessionId, postId, imageUrl) {
  const posts = getPosts(sessionId);
  const post = posts.find((p) => p.id === postId);
  if (post) {
    post.hasImage = true;
    post.imageUrl = imageUrl;
    notify(sessionId);
  }
}

// Patch a post's editable body fields (text[], hashtags[], cta).
// Undefined keys are left unchanged.
//
// Also accepts the runtime regenerate flags driven by draft-rewrite.js
// (`isRegenerating`, `regenerateStage`). These never appear in seeded
// mocks — they're transient state set during the streaming flow. Pass
// `null` or `false` to clear them.
export function updatePostContent(sessionId, postId, partial) {
  const posts = getPosts(sessionId);
  const post = posts.find((p) => p.id === postId);
  if (!post) return;
  if (partial.text !== undefined) post.text = partial.text;
  if (partial.hashtags !== undefined) post.hashtags = partial.hashtags;
  if (partial.cta !== undefined) post.cta = partial.cta;
  if (partial.isRegenerating !== undefined) post.isRegenerating = partial.isRegenerating;
  if (partial.regenerateStage !== undefined) post.regenerateStage = partial.regenerateStage;
  notify(sessionId);
}

// Remove a post from the session's drafts list. Returns the removed post
// (or null) so the caller can offer Undo via re-insertion.
export function removePost(sessionId, postId) {
  const posts = getPosts(sessionId);
  const idx = posts.findIndex((p) => p.id === postId);
  if (idx < 0) return null;
  const [removed] = posts.splice(idx, 1);
  notify(sessionId);
  return removed;
}

// Re-insert a previously removed post at its original index (used by the
// Undo action of the trash-button toast).
export function insertPost(sessionId, post, index = 0) {
  const posts = getPosts(sessionId);
  posts.splice(index, 0, post);
  notify(sessionId);
}

export function subscribe(sessionId, fn) {
  if (!subs.has(sessionId)) subs.set(sessionId, new Set());
  subs.get(sessionId).add(fn);
  return () => {
    const set = subs.get(sessionId);
    if (set) set.delete(fn);
  };
}

// Drop all posts + subscribers for a session — used by the
// conversation-delete flow in the sidebar.
export function clearSession(sessionId) {
  store.delete(sessionId);
  const set = subs.get(sessionId);
  if (set) {
    for (const fn of set) {
      try {
        fn([]);
      } catch {}
    }
    subs.delete(sessionId);
  }
}

// --- Internals ----------------------------------------------------------

function seed(sessionId) {
  // Mirrors library.js: only demo sessions (s-acme-launch / s-riverside /
  // etc.) get the seeded posts mock. New conversations created at runtime
  // start empty so the user doesn't see "5 drafts" appear in a chat they
  // just opened from "+ New conversation".
  //
  // Pulls from the per-session bucket in mocks (`postsBySession`) so each
  // demo session has its own distinct drafts list. Shallow-copy each post
  // so edits don't leak across sessions or mutate the shared mock array.
  const shouldSeed = !isNewUser() && DEMO_SESSION_IDS.has(sessionId);
  const seedForSession = shouldSeed ? seedPostsBySession[sessionId] || [] : [];
  store.set(
    sessionId,
    seedForSession.map((p) => ({ ...p })),
  );
}

function notify(sessionId) {
  const set = subs.get(sessionId);
  if (!set) return;
  const snapshot = store.get(sessionId).slice();
  set.forEach((fn) => fn(snapshot));
}
